### PR TITLE
Update vcpkg version used by GitHub Actions

### PR DESCRIPTION
**Pull request by mitza-oci**

### CODE REVIEW

**Comment by iguessthislldo** [comment]
@mitza-oci Is the error related to https://github.com/OpenDDS/OpenDDS/pull/4519?

**Comment by mitza-oci** [comment]
> @mitza-oci Is the error related to [OpenDDS/OpenDDS#4519](https://github.com/OpenDDS/OpenDDS/pull/4519)?

This is building with Werror?

**Comment by iguessthislldo** [comment]
Yes, way in back of this line:

https://github.com/OpenDDS/opendds-monitor/blob/39c38579479f88411f287956ef2b66c2048a9524/test/CMakeLists.txt#L6

**Comment by mitza-oci** [comment]
> Yes, way in back of this line:
> 

Would be good to have that tested upstream.

**Comment by iguessthislldo** [comment]
I agree. Since it looks like the release is working, I wait for the Windows one to finish and then approve it.

**Comment by mitza-oci** [comment]
> I agree. Since it looks like the release is working, I wait for the Windows one to finish and then approve it.

And it failed without my PR https://github.com/OpenDDS/opendds-monitor/actions/runs/8405526105

I'll have a fix for OpenDDS/OpenDDS soon.

**Review by iguessthislldo — APPROVED** [review]

**Pull request merged**
